var namespace_microsoft_1_1_bot_1_1_builder =
[
    [ "Form", "dd/dc9/namespace_microsoft_1_1_bot_1_1_builder_1_1_form.html", "dd/dc9/namespace_microsoft_1_1_bot_1_1_builder_1_1_form" ],
    [ "Models", "d2/dd9/namespace_microsoft_1_1_bot_1_1_builder_1_1_models.html", "d2/dd9/namespace_microsoft_1_1_bot_1_1_builder_1_1_models" ],
    [ "CallStackSerializer", "d3/dbd/class_microsoft_1_1_bot_1_1_builder_1_1_call_stack_serializer.html", "d3/dbd/class_microsoft_1_1_bot_1_1_builder_1_1_call_stack_serializer" ],
    [ "CommandDialog", "d7/d5e/class_microsoft_1_1_bot_1_1_builder_1_1_command_dialog.html", "d7/d5e/class_microsoft_1_1_bot_1_1_builder_1_1_command_dialog" ],
    [ "ConnectorSession", "d4/d94/class_microsoft_1_1_bot_1_1_builder_1_1_connector_session.html", "d4/d94/class_microsoft_1_1_bot_1_1_builder_1_1_connector_session" ],
    [ "ConsoleSession", "d3/dab/class_microsoft_1_1_bot_1_1_builder_1_1_console_session.html", "d3/dab/class_microsoft_1_1_bot_1_1_builder_1_1_console_session" ],
    [ "CookieHelper", "da/d17/class_microsoft_1_1_bot_1_1_builder_1_1_cookie_helper.html", "da/d17/class_microsoft_1_1_bot_1_1_builder_1_1_cookie_helper" ],
    [ "CookieStore", "df/ddf/class_microsoft_1_1_bot_1_1_builder_1_1_cookie_store.html", "df/ddf/class_microsoft_1_1_bot_1_1_builder_1_1_cookie_store" ],
    [ "Dialog", "d1/dd9/class_microsoft_1_1_bot_1_1_builder_1_1_dialog.html", "d1/dd9/class_microsoft_1_1_bot_1_1_builder_1_1_dialog" ],
    [ "DialogCollection", "d4/dd1/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_collection.html", "d4/dd1/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_collection" ],
    [ "DialogResult", "d3/d7b/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_result.html", "d3/d7b/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_result" ],
    [ "DialogResumeHandler", "de/d54/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_resume_handler.html", "de/d54/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_resume_handler" ],
    [ "DialogState", "d7/dac/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_state.html", "d7/dac/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_state" ],
    [ "IDialog", "da/d12/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog.html", "da/d12/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog" ],
    [ "IDialogCollection", "db/d9a/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog_collection.html", "db/d9a/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog_collection" ],
    [ "InMemoryStore", "d9/d12/class_microsoft_1_1_bot_1_1_builder_1_1_in_memory_store.html", "d9/d12/class_microsoft_1_1_bot_1_1_builder_1_1_in_memory_store" ],
    [ "ISession", "d8/d04/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session.html", "d8/d04/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session" ],
    [ "ISessionData", "df/d4b/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session_data.html", "df/d4b/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session_data" ],
    [ "ISessionStore", "dc/dfe/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session_store.html", "dc/dfe/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session_store" ],
    [ "LuisDialog", "d4/d86/class_microsoft_1_1_bot_1_1_builder_1_1_luis_dialog.html", "d4/d86/class_microsoft_1_1_bot_1_1_builder_1_1_luis_dialog" ],
    [ "LuisResult", "de/d55/class_microsoft_1_1_bot_1_1_builder_1_1_luis_result.html", "de/d55/class_microsoft_1_1_bot_1_1_builder_1_1_luis_result" ],
    [ "MessageStore", "de/d84/class_microsoft_1_1_bot_1_1_builder_1_1_message_store.html", "de/d84/class_microsoft_1_1_bot_1_1_builder_1_1_message_store" ],
    [ "PromptDialog", "d9/ddc/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog.html", "d9/ddc/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog" ],
    [ "PromptDialogArgs", "d1/d5c/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog_args.html", "d1/d5c/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog_args" ],
    [ "PromptDialogResult", "d5/dee/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog_result.html", "d5/dee/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog_result" ],
    [ "Prompts", "de/db4/class_microsoft_1_1_bot_1_1_builder_1_1_prompts.html", "de/db4/class_microsoft_1_1_bot_1_1_builder_1_1_prompts" ],
    [ "Session", "d9/d33/class_microsoft_1_1_bot_1_1_builder_1_1_session.html", "d9/d33/class_microsoft_1_1_bot_1_1_builder_1_1_session" ],
    [ "SessionState", "d7/dd6/class_microsoft_1_1_bot_1_1_builder_1_1_session_state.html", "d7/dd6/class_microsoft_1_1_bot_1_1_builder_1_1_session_state" ],
    [ "WaitHandleEx", "d1/dec/class_microsoft_1_1_bot_1_1_builder_1_1_wait_handle_ex.html", "d1/dec/class_microsoft_1_1_bot_1_1_builder_1_1_wait_handle_ex" ]
];