var namespace_microsoft_1_1_bot_1_1_builder =
[
    [ "Form", "dd/dc9/namespace_microsoft_1_1_bot_1_1_builder_1_1_form.html", "dd/dc9/namespace_microsoft_1_1_bot_1_1_builder_1_1_form" ],
    [ "Models", "d2/dd9/namespace_microsoft_1_1_bot_1_1_builder_1_1_models.html", "d2/dd9/namespace_microsoft_1_1_bot_1_1_builder_1_1_models" ],
    [ "CallDialog", "d0/dd4/class_microsoft_1_1_bot_1_1_builder_1_1_call_dialog.html", "d0/dd4/class_microsoft_1_1_bot_1_1_builder_1_1_call_dialog" ],
    [ "CommandDialog", "d7/d5e/class_microsoft_1_1_bot_1_1_builder_1_1_command_dialog.html", "d7/d5e/class_microsoft_1_1_bot_1_1_builder_1_1_command_dialog" ],
    [ "ConnectorSession", "d4/d94/class_microsoft_1_1_bot_1_1_builder_1_1_connector_session.html", "d4/d94/class_microsoft_1_1_bot_1_1_builder_1_1_connector_session" ],
    [ "ConsoleSession", "d3/dab/class_microsoft_1_1_bot_1_1_builder_1_1_console_session.html", "d3/dab/class_microsoft_1_1_bot_1_1_builder_1_1_console_session" ],
    [ "CookieHelper", "da/d17/class_microsoft_1_1_bot_1_1_builder_1_1_cookie_helper.html", "da/d17/class_microsoft_1_1_bot_1_1_builder_1_1_cookie_helper" ],
    [ "CookieStore", "df/ddf/class_microsoft_1_1_bot_1_1_builder_1_1_cookie_store.html", "df/ddf/class_microsoft_1_1_bot_1_1_builder_1_1_cookie_store" ],
    [ "Dialog", "d1/dd9/class_microsoft_1_1_bot_1_1_builder_1_1_dialog.html", "d1/dd9/class_microsoft_1_1_bot_1_1_builder_1_1_dialog" ],
    [ "DialogCollection", "d4/dd1/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_collection.html", "d4/dd1/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_collection" ],
    [ "DialogException", "d2/d46/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_exception.html", "d2/d46/class_microsoft_1_1_bot_1_1_builder_1_1_dialog_exception" ],
    [ "Extensions", "dd/d63/class_microsoft_1_1_bot_1_1_builder_1_1_extensions.html", "dd/d63/class_microsoft_1_1_bot_1_1_builder_1_1_extensions" ],
    [ "Field", "d8/dd9/class_microsoft_1_1_bot_1_1_builder_1_1_field.html", "d8/dd9/class_microsoft_1_1_bot_1_1_builder_1_1_field" ],
    [ "IDialog", "da/d12/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog.html", "da/d12/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog" ],
    [ "IDialogCollection", "db/d9a/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog_collection.html", "db/d9a/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog_collection" ],
    [ "IDialogFrame", "d1/dd7/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog_frame.html", "d1/dd7/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog_frame" ],
    [ "IDialogStack", "d5/dd1/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog_stack.html", "d5/dd1/interface_microsoft_1_1_bot_1_1_builder_1_1_i_dialog_stack" ],
    [ "InMemoryStore", "d9/d12/class_microsoft_1_1_bot_1_1_builder_1_1_in_memory_store.html", null ],
    [ "InvalidSessionException", "d1/d43/class_microsoft_1_1_bot_1_1_builder_1_1_invalid_session_exception.html", "d1/d43/class_microsoft_1_1_bot_1_1_builder_1_1_invalid_session_exception" ],
    [ "ISession", "d8/d04/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session.html", "d8/d04/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session" ],
    [ "ISessionData", "df/d4b/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session_data.html", "df/d4b/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session_data" ],
    [ "ISessionStore", "dc/dfe/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session_store.html", "dc/dfe/interface_microsoft_1_1_bot_1_1_builder_1_1_i_session_store" ],
    [ "LuisDialog", "d4/d86/class_microsoft_1_1_bot_1_1_builder_1_1_luis_dialog.html", "d4/d86/class_microsoft_1_1_bot_1_1_builder_1_1_luis_dialog" ],
    [ "LuisIntent", "d7/da6/class_microsoft_1_1_bot_1_1_builder_1_1_luis_intent.html", "d7/da6/class_microsoft_1_1_bot_1_1_builder_1_1_luis_intent" ],
    [ "LuisModel", "df/d41/class_microsoft_1_1_bot_1_1_builder_1_1_luis_model.html", "df/d41/class_microsoft_1_1_bot_1_1_builder_1_1_luis_model" ],
    [ "LuisResult", "de/d55/class_microsoft_1_1_bot_1_1_builder_1_1_luis_result.html", "de/d55/class_microsoft_1_1_bot_1_1_builder_1_1_luis_result" ],
    [ "MessageStore", "de/d84/class_microsoft_1_1_bot_1_1_builder_1_1_message_store.html", "de/d84/class_microsoft_1_1_bot_1_1_builder_1_1_message_store" ],
    [ "PromptDialog", "d9/ddc/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog.html", "d9/ddc/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog" ],
    [ "PromptDialogArgs", "d1/d5c/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog_args.html", "d1/d5c/class_microsoft_1_1_bot_1_1_builder_1_1_prompt_dialog_args" ],
    [ "Prompts", "de/db4/class_microsoft_1_1_bot_1_1_builder_1_1_prompts.html", "de/db4/class_microsoft_1_1_bot_1_1_builder_1_1_prompts" ],
    [ "Session", "d9/d33/class_microsoft_1_1_bot_1_1_builder_1_1_session.html", "d9/d33/class_microsoft_1_1_bot_1_1_builder_1_1_session" ],
    [ "StackDisciplineException", "d1/dba/class_microsoft_1_1_bot_1_1_builder_1_1_stack_discipline_exception.html", "d1/dba/class_microsoft_1_1_bot_1_1_builder_1_1_stack_discipline_exception" ],
    [ "TaskNotCompletedException", "da/d55/class_microsoft_1_1_bot_1_1_builder_1_1_task_not_completed_exception.html", "da/d55/class_microsoft_1_1_bot_1_1_builder_1_1_task_not_completed_exception" ],
    [ "Tasks", "d7/d51/class_microsoft_1_1_bot_1_1_builder_1_1_tasks.html", "d7/d51/class_microsoft_1_1_bot_1_1_builder_1_1_tasks" ],
    [ "WaitHandleEx", "d1/dec/class_microsoft_1_1_bot_1_1_builder_1_1_wait_handle_ex.html", "d1/dec/class_microsoft_1_1_bot_1_1_builder_1_1_wait_handle_ex" ]
];