en-us
{"Text":null,"Integer":0,"Float":null,"SomeChoices":0,"Date":"0001-01-01T00:00:00"}
[]
FromUser:"Hi"
1
ToUserText:"Please enter a number for float "
State:{"Text":null,"Integer":0,"Float":null,"SomeChoices":0,"Date":"0001-01-01T00:00:00"}
FromUser:"1.0"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":null,"subtitle":null,"text":"Please select a some choices ","images":null,"buttons":[{"type":"imBack","title":"One","image":null,"value":"One"},{"type":"imBack","title":"Two","image":null,"value":"Two"},{"type":"imBack","title":"Three","image":null,"value":"Three"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Text":null,"Integer":0,"Float":1.0,"SomeChoices":0,"Date":"0001-01-01T00:00:00"}
FromUser:"one"
1
ToUserText:"Please enter a number for float "
State:{"Text":null,"Integer":0,"Float":null,"SomeChoices":1,"Date":"0001-01-01T00:00:00"}
FromUser:"2.0"
1
ToUserText:"All OK?"
State:{"Text":null,"Integer":0,"Float":2.0,"SomeChoices":1,"Date":"0001-01-01T00:00:00"}
FromUser:"no"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":null,"subtitle":null,"text":"What do you want to change? ","images":null,"buttons":[{"type":"imBack","title":"Float(2)","image":null,"value":"Float"},{"type":"imBack","title":"Some Choices(One)","image":null,"value":"Some Choices"},{"type":"imBack","title":"No Preference","image":null,"value":"No Preference"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Text":null,"Integer":0,"Float":2.0,"SomeChoices":1,"Date":"0001-01-01T00:00:00"}
FromUser:"Some Choices"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":null,"subtitle":null,"text":"Please select a some choices ","images":null,"buttons":[{"type":"imBack","title":"One","image":null,"value":"One"},{"type":"imBack","title":"Two","image":null,"value":"Two"},{"type":"imBack","title":"Three","image":null,"value":"Three"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Text":null,"Integer":0,"Float":2.0,"SomeChoices":1,"Date":"0001-01-01T00:00:00"}
FromUser:"one"
1
ToUserText:"Please enter a number for float "
State:{"Text":null,"Integer":0,"Float":null,"SomeChoices":1,"Date":"0001-01-01T00:00:00"}
FromUser:"3.0"
1
ToUserText:"All OK?"
State:{"Text":null,"Integer":0,"Float":3.0,"SomeChoices":1,"Date":"0001-01-01T00:00:00"}
FromUser:"no"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":null,"subtitle":null,"text":"What do you want to change? ","images":null,"buttons":[{"type":"imBack","title":"Float(3)","image":null,"value":"Float"},{"type":"imBack","title":"Some Choices(One)","image":null,"value":"Some Choices"},{"type":"imBack","title":"No Preference","image":null,"value":"No Preference"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Text":null,"Integer":0,"Float":3.0,"SomeChoices":1,"Date":"0001-01-01T00:00:00"}
FromUser:"some choices"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":null,"subtitle":null,"text":"Please select a some choices ","images":null,"buttons":[{"type":"imBack","title":"One","image":null,"value":"One"},{"type":"imBack","title":"Two","image":null,"value":"Two"},{"type":"imBack","title":"Three","image":null,"value":"Three"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Text":null,"Integer":0,"Float":3.0,"SomeChoices":1,"Date":"0001-01-01T00:00:00"}
FromUser:"two"
1
ToUserText:"All OK?"
State:{"Text":null,"Integer":0,"Float":3.0,"SomeChoices":2,"Date":"0001-01-01T00:00:00"}
FromUser:"yes"
0
State:{"Text":null,"Integer":0,"Float":3.0,"SomeChoices":2,"Date":"0001-01-01T00:00:00"}
Result: {"Text":null,"Integer":0,"Float":3.0,"SomeChoices":2,"Date":"0001-01-01T00:00:00"}
